//! CUDA code templates for decision logic functions.
//!
//! Each template mirrors the corresponding Rust function in bt-signals and bt-core.
//! Decision logic covers: gates, signals, exits (SL/TSL/TP/smart), sizing, and cooldowns.
//!
//! Templates are stubs (returning empty strings) until their respective tickets implement them:
//! - AQC-1210: check_gates_codegen()
//! - AQC-1211: generate_signal_codegen()
//! - AQC-1220: compute_sl_price_codegen()
//! - AQC-1221: compute_trailing_codegen()
//! - AQC-1222: check_tp_codegen()
//! - AQC-1223: check_smart_exits_codegen()
//! - AQC-1224: check_all_exits_codegen()
//! - AQC-1230: compute_entry_size_codegen()
//! - AQC-1231: is_pesc_blocked_codegen()

/// File header for the generated decision CUDA source.
pub const DECISION_HEADER: &str = "\
// =============================================================================
// AUTO-GENERATED from bt-signals + bt-core kernel source -- DO NOT EDIT
// Generated by bt-gpu/build.rs decision codegen
// =============================================================================
//
// These device functions mirror the Rust decision logic in:
//   bt-signals/src/gates.rs      -- gate evaluation
//   bt-signals/src/entry.rs      -- signal generation
//   bt-core/src/exits/*.rs       -- stop loss, trailing, take profit, smart exits
//   bt-core/src/engine.rs        -- sizing, cooldowns
//
// Source of truth: Rust kernel code. GPU code is derived, not independent.
// =============================================================================

#pragma once
";

// The SOURCE_HASHES line will be injected by the drift detector (AQC-1200)

/// Gates: 8 gates + TMC/AVE + DRE (AQC-1210)
pub fn check_gates_codegen() -> String { String::new() /* stub */ }

/// Signals: Mode 1/2/3 + MACD helpers (AQC-1211)
pub fn generate_signal_codegen() -> String { String::new() /* stub */ }

/// Stop loss: ASE/DASE/SLB/breakeven (AQC-1220)
pub fn compute_sl_price_codegen() -> String { String::new() /* stub */ }

/// Trailing stop: VBTS/TATP/TSPV/ratchet (AQC-1221)
pub fn compute_trailing_codegen() -> String { String::new() /* stub */ }

/// Take profit: partial TP + full TP ladder (AQC-1222)
pub fn check_tp_codegen() -> String { String::new() /* stub */ }

/// Smart exits: all 8 sub-checks (AQC-1223)
pub fn check_smart_exits_codegen() -> String { String::new() /* stub */ }

/// Exit orchestrator: priority dispatch (AQC-1224)
pub fn check_all_exits_codegen() -> String { String::new() /* stub */ }

/// Entry sizing: dynamic sizing/leverage/vol scalar (AQC-1230)
pub fn compute_entry_size_codegen() -> String { String::new() /* stub */ }

/// PESC cooldown: reentry cooldown + ADX interpolation (AQC-1231)
pub fn is_pesc_blocked_codegen() -> String { String::new() /* stub */ }
