"""Shared legacy strategy defaults extracted from `mei_alpha_v1.py`.

This module exists so compatibility consumers can read default config and
fallback symbols without importing the full legacy trader/runtime module.
"""

from __future__ import annotations

import os


def _env_float(name: str, default: float) -> float:
    try:
        return float(os.getenv(name, str(default)))
    except Exception:
        return float(default)


FALLBACK_SYMBOLS = [
    "BTC",
    "ETH",
    "SOL",
    "HYPE",
    "XRP",
    "ARB",
    "OP",
    "SUI",
    "AVAX",
    "APT",
    "LINK",
    "NEAR",
    "LTC",
    "BCH",
    "XLM",
    "ADA",
    "DOT",
    "STX",
    "POL",
    "TIA",
]

ALLOCATION_PCT = _env_float("AI_QUANT_ALLOCATION_PCT", 0.03)
TP_ATR_MULT = 4.0
HL_DEFAULT_LEVERAGE = _env_float("HL_DEFAULT_LEVERAGE", 3.0)
HL_SLIPPAGE_BPS = _env_float("HL_SLIPPAGE_BPS", 10.0)

DEFAULT_STRATEGY_CONFIG = {
    "trade": {
        "allocation_pct": ALLOCATION_PCT,
        "sl_atr_mult": 2.0,
        "tp_atr_mult": TP_ATR_MULT,
        "leverage": HL_DEFAULT_LEVERAGE,
        "enable_reef_filter": True,
        "reef_long_rsi_block_gt": 70.0,
        "reef_short_rsi_block_lt": 30.0,
        "reef_adx_threshold": 45.0,
        "reef_long_rsi_extreme_gt": 75.0,
        "reef_short_rsi_extreme_lt": 25.0,
        "leverage_low": 1.0,
        "leverage_medium": 3.0,
        "leverage_high": 5.0,
        "slippage_bps": HL_SLIPPAGE_BPS,
        "use_bbo_for_fills": True,
        "min_notional_usd": 10.0,
        "bump_to_min_notional": False,
        "max_total_margin_pct": 0.60,
        "enable_dynamic_sizing": True,
        "confidence_mult_high": 1.0,
        "confidence_mult_medium": 0.7,
        "confidence_mult_low": 0.5,
        "adx_sizing_min_mult": 0.6,
        "adx_sizing_full_adx": 40.0,
        "vol_baseline_pct": 0.01,
        "vol_scalar_min": 0.5,
        "vol_scalar_max": 1.0,
        "enable_pyramiding": True,
        "max_adds_per_symbol": 2,
        "add_fraction_of_base_margin": 0.5,
        "add_cooldown_minutes": 60,
        "add_min_profit_atr": 0.5,
        "add_min_confidence": "medium",
        "entry_min_confidence": "high",
        "enable_partial_tp": True,
        "tp_partial_pct": 0.5,
        "tp_partial_min_notional_usd": 10.0,
        "tp_partial_atr_mult": 0.0,
        "trailing_start_atr": 1.0,
        "trailing_distance_atr": 0.8,
        "enable_ssf_filter": True,
        "enable_breakeven_stop": True,
        "breakeven_start_atr": 0.7,
        "breakeven_buffer_atr": 0.05,
        "enable_rsi_overextension_exit": True,
        "rsi_exit_profit_atr_switch": 1.5,
        "rsi_exit_ub_lo_profit": 80.0,
        "rsi_exit_ub_hi_profit": 70.0,
        "rsi_exit_lb_lo_profit": 20.0,
        "rsi_exit_lb_hi_profit": 30.0,
        "reentry_cooldown_minutes": 60,
        "reentry_cooldown_min_mins": 45,
        "reentry_cooldown_max_mins": 180,
        "enable_vol_buffered_trailing": True,
        "tsme_min_profit_atr": 1.0,
        "tsme_require_adx_slope_negative": True,
        "min_atr_pct": 0.003,
        "reverse_entry_signal": False,
        "block_exits_on_extreme_dev": False,
        "glitch_price_dev_pct": 0.40,
        "glitch_atr_mult": 12.0,
        "trailing_start_atr_low_conf": 0.0,
        "trailing_distance_atr_low_conf": 0.0,
        "smart_exit_adx_exhaustion_lt": 18.0,
        "smart_exit_adx_exhaustion_lt_low_conf": 0.0,
        "rsi_exit_ub_lo_profit_low_conf": 0.0,
        "rsi_exit_ub_hi_profit_low_conf": 0.0,
        "rsi_exit_lb_lo_profit_low_conf": 0.0,
        "rsi_exit_lb_hi_profit_low_conf": 0.0,
        "max_open_positions": 20,
        "entry_cooldown_s": 20,
        "exit_cooldown_s": 15,
        "max_entry_orders_per_loop": 6,
    },
    "indicators": {
        "ema_slow_window": 50,
        "ema_fast_window": 20,
        "ema_macro_window": 200,
        "adx_window": 14,
        "bb_window": 20,
        "bb_width_avg_window": 30,
        "atr_window": 14,
        "rsi_window": 14,
        "vol_sma_window": 20,
        "vol_trend_window": 5,
        "stoch_rsi_window": 14,
        "stoch_rsi_smooth1": 3,
        "stoch_rsi_smooth2": 3,
    },
    "filters": {
        "enable_ranging_filter": True,
        "enable_anomaly_filter": True,
        "enable_extension_filter": True,
        "require_adx_rising": True,
        "adx_rising_saturation": 40.0,
        "require_volume_confirmation": False,
        "vol_confirm_include_prev": True,
        "use_stoch_rsi_filter": True,
        "require_btc_alignment": True,
        "require_macro_alignment": False,
    },
    "market_regime": {
        "enable_regime_filter": False,
        "breadth_block_short_above": 90.0,
        "breadth_block_long_below": 10.0,
        "enable_auto_reverse": False,
        "auto_reverse_breadth_low": 10.0,
        "auto_reverse_breadth_high": 90.0,
        "enable_regime_gate": False,
        "regime_gate_breadth_low": 20.0,
        "regime_gate_breadth_high": 80.0,
        "regime_gate_btc_adx_min": 20.0,
        "regime_gate_btc_atr_pct_min": 0.003,
        "regime_gate_fail_open": False,
    },
    "watchlist_exclude": [],
    "thresholds": {
        "entry": {
            "min_adx": 22.0,
            "high_conf_volume_mult": 2.5,
            "btc_adx_override": 40.0,
            "max_dist_ema_fast": 0.04,
            "ave_enabled": True,
            "ave_atr_ratio_gt": 1.5,
            "ave_adx_mult": 1.25,
            "ave_avg_atr_window": 50,
            "macd_hist_entry_mode": "accel",
            "enable_pullback_entries": False,
            "pullback_confidence": "low",
            "pullback_min_adx": 22.0,
            "pullback_rsi_long_min": 50.0,
            "pullback_rsi_short_max": 50.0,
            "pullback_require_macd_sign": True,
            "enable_slow_drift_entries": False,
            "slow_drift_slope_window": 20,
            "slow_drift_min_slope_pct": 0.0006,
            "slow_drift_min_adx": 10.0,
            "slow_drift_rsi_long_min": 50.0,
            "slow_drift_rsi_short_max": 50.0,
            "slow_drift_require_macd_sign": True,
        },
        "ranging": {
            "min_signals": 2,
            "adx_below": 21.0,
            "bb_width_ratio_below": 0.8,
            "rsi_low": 47.0,
            "rsi_high": 53.0,
        },
        "anomaly": {
            "price_change_pct_gt": 0.10,
            "ema_fast_dev_pct_gt": 0.50,
        },
        "tp_and_momentum": {
            "adx_strong_gt": 40.0,
            "adx_weak_lt": 30.0,
            "tp_mult_strong": 7.0,
            "tp_mult_weak": 3.0,
            "rsi_long_strong": 52.0,
            "rsi_long_weak": 56.0,
            "rsi_short_strong": 48.0,
            "rsi_short_weak": 44.0,
        },
        "stoch_rsi": {
            "block_long_if_k_gt": 0.85,
            "block_short_if_k_lt": 0.15,
        },
    },
}

# Compatibility aliases for existing imports.
_FALLBACK_SYMBOLS = FALLBACK_SYMBOLS
_DEFAULT_STRATEGY_CONFIG = DEFAULT_STRATEGY_CONFIG
